# Proxstar
VM_EXPIRE_MONTHS = 3

# Proxmox
PROXMOX_HOST = ''
PROXMOX_USER = ''
PROXMOX_PASS = ''
PROXMOX_ISO_STORAGE = ''

# STARRS
STARRS_DB_HOST = ''
STARRS_DB_NAME = ''
STARRS_DB_USER = ''
STARRS_DB_PASS = ''
STARRS_IP_RANGE = ''
